use octocrab::Octocrab;

/// GitHub PR comment bot.
/// Posts a comment on a PR with the preview deployment URL when a deployment
/// is created, and updates the comment when the build completes.
pub struct PrBot {
    github: Octocrab,
}

impl PrBot {
    /// Create a new PR bot from a GitHub token.
    /// If no token is configured, returns None — bot is disabled.
    pub fn new(token: &str) -> Option<Self> {
        if token.is_empty() {
            return None;
        }
        let github = Octocrab::builder()
            .personal_token(token.to_string())
            .build()
            .ok()?;
        Some(Self { github })
    }

    /// Post a comment on a PR announcing the deployment.
    /// Returns the comment ID so we can update it later.
    pub async fn post_deployment_comment(
        &self,
        repo_full_name: &str,
        pr_number: u64,
        deployment_url: &str,
        deployment_id: &str,
    ) -> anyhow::Result<u64> {
        let (owner, repo) = split_repo(repo_full_name)?;

        let body = format!(
            "## 🚀 Preview Deployment\n\n\
            **Status:** Building…\n\n\
            **URL:** http://{deployment_url}\n\n\
            **Deployment ID:** `{deployment_id}`\n\n\
            ---\n\
            _This comment was automatically generated by vercel-clone._"
        );

        let comment = self
            .github
            .issues(owner, repo)
            .create_comment(pr_number, body)
            .await?;

        tracing::info!(
            "Posted PR comment #{} on {}/{}#{} for deployment {}",
            comment.id,
            owner,
            repo,
            pr_number,
            deployment_id
        );

        Ok(comment.id.0)
    }

    /// Update an existing PR comment with build results.
    pub async fn update_deployment_comment(
        &self,
        repo_full_name: &str,
        comment_id: u64,
        status: &str,
        deployment_url: &str,
        deployment_id: &str,
        framework: Option<&str>,
        error: Option<&str>,
    ) -> anyhow::Result<()> {
        let (owner, repo) = split_repo(repo_full_name)?;

        let (status_emoji, status_line) = match status {
            "ready" => ("✅", "Ready"),
            "error" => ("❌", "Failed"),
            "building" => ("🔄", "Building…"),
            _ => ("⏳", &*format!("Status: {}", status)),
        };

        let framework_line = framework
            .map(|f| format!("**Framework:** `{}`\n\n", f))
            .unwrap_or_default();

        let error_line = error
            .map(|e| format!("**Error:**\n```\n{}\n```\n\n", truncate(e, 500)))
            .unwrap_or_default();

        let body = format!(
            "## 🚀 Preview Deployment\n\n\
            **Status:** {status_emoji} {status_line}\n\n\
            {framework_line}\
            {error_line}\
            **URL:** http://{deployment_url}\n\n\
            **Deployment ID:** `{deployment_id}`\n\n\
            ---\n\
            _This comment was automatically generated by vercel-clone._"
        );

        self.github
            .issues(owner, repo)
            .update_comment(comment_id.into(), body)
            .await?;

        tracing::info!(
            "Updated PR comment {} for deployment {} (status: {})",
            comment_id,
            deployment_id,
            status
        );

        Ok(())
    }
}

/// Split "owner/repo" into ("owner", "repo").
fn split_repo(full_name: &str) -> anyhow::Result<(&str, &str)> {
    let parts: Vec<&str> = full_name.splitn(2, '/').collect();
    if parts.len() != 2 {
        anyhow::bail!("Invalid repo full name: {}", full_name);
    }
    Ok((parts[0], parts[1]))
}

/// Truncate a string to max_len, appending "..." if truncated.
fn truncate(s: &str, max_len: usize) -> String {
    if s.len() <= max_len {
        s.to_string()
    } else {
        format!("{}...", &s[..max_len])
    }
}
